### ISSUE TITLE
Criar site/blog

### ISSUE THREAD

**Issue by turicas** [GruPyPR/grupypr.github.io#10]
- [x] Renomear repositório para grupypr.github.io
- [x] Criar site básico com com pelican
- [x] Escrever relato do encontro de 12/02/2017
- [x] Publicar novo site usando GitHub Pages

**Comment by LuanComputacao** [comment]
Quais os procedimentos para fazer parte, @turicas ?

**Comment by turicas** [comment]
@LuanComputacao, fazer parte do GruPy-PR? É só entrar nos grupos online que usamos e começar a ir aos encontros - é tudo gratuito! :) Tem links para o grupo no Telegram e Google Groups no fim da publicação que fiz: http://grupypr.github.io/2017/primeiro-encontro-do-ano.html
