### ISSUE TITLE
Mover conteúdo da wiki para site/blog

### ISSUE THREAD

**Issue by turicas** [GruPyPR/grupypr.github.io#12]
Existem relatos de encontros que estão na wiki. Para centralizar e dar mais visiblidade a essa informação, acho interessante movê-los para o site (cada encontro seria um post no blog) e desabilitar a wiki.

**Comment by turicas** [comment]
Tem a ver com #9 (duplicada?).

**Comment by ellisonleao** [comment]
Deixa essa, mais recente. Vou fechar a outra
