### ISSUE TITLE
Criar arquivo CONTRIBUTING

### ISSUE THREAD

**Issue by ellisonleao** [GruPyPR/grupypr.github.io#14]
Novas informações que devem ser colocadas no CONTRIBUTING:

- Como criar o ambiente de desenvolvimento
- Como adicionar novo post
- Como adicionar novo autor
- Como adicionar uma nova página
- Como publicar as alterações no Github Pages
- Como criar/validar Pull requests

**Comment by marcelobelli** [comment]
Deixa comigo

**Comment by ellisonleao** [comment]
@marcelobelli se precisar de ajuda, me fala

**Comment by marcelobelli** [comment]
Comecei a ver certinho os tópicos. Estava pensando no seguinte:

# Baixar o src
- Fork Blog
- git clone Blog
- cd grupypr.github.io
- python -m venv .grupyprblog
- source .grupyprblog/bin/activate
- pip install -r requirements.txt

# Manter src atualizado
- git remote add upstream https://github.com/GruPyPR/grupypr.github.io.git
- git checkout src
- git rebase upstream/src
- git push

O que acham?

Falta agora a parte do Pelican, mas como não sei mexer nele estou tendo que aprender :)

**Comment by ellisonleao** [comment]
Eu separaria mais ou menos assim:

----------------------------------------

[Alguma msg de agradecimento sobre a intenção de contribuir com o projeto]

# Instalando e rodando o projeto

[Alguma msg introdutória]

## Fork do projeto 

- Passo 1 
```python
codigo!
```
- Passo 2

```python
codigo
```
etc..

# Criando Pull request

[msg introdutória]

- Passo 1
```
código
```

- Passo 2

```
código
```

**Comment by marcelobelli** [comment]
Alguém dá uma olhadinha! #22

**Comment by ellisonleao** [comment]
Fechando. #22
