### ISSUE TITLE
Permitir participação remota

### ISSUE THREAD

**Issue by wiliamsouza** [GruPyPR/grupypr.github.io#3]
Criar um documento de como participar remotamente do grupo.
- Mumble
- Hangout

**Comment by wiliamsouza** [comment]
Vamos usar o server de mumble do GaragemHacker:

 garagemhacker.sytes.net

Um  contra é que todos teriam que ter o mumble ou no CPU ou no phone com phones de ouvido.
- Documentar como configurar no computador
- Colocar links para outras apps

**Comment by leonardossrocha** [comment]
Eu posso criar o documento de como participar no Hangout se quiser. Posso startar essa tarefa?

**Comment by ramiroluz** [comment]
Sim. \o/

On Wed, Sep 9, 2015 at 9:06 PM, Leonardo Rocha notifications@github.com
wrote:

> Eu posso criar o documento de como participar no Hangout se quiser. Posso
> startar essa tarefa?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GruPyPR/encontros/issues/3#issuecomment-139077149.

## 

## 

-- Ramiro Batista da Luz
-- (41) 9173-2231
-- http://www.ramiroluz.eti.br

**Comment by leonardossrocha** [comment]
@ramiroluz peço desculpas pois ainda não consegui montar o vídeo pra mostrar como utilizar o Hangout. Penso que seria interessante ter as duas pontas, a pessoa que gera a transmissão e a pessoa que participa dela, pra mostrar da maneira mais real possível como funciona a ferramenta. Assim sendo, pensei em marcar com um de vocês para que façamos as gravações pra gerar o tutorial ensinando como utilizar o Hangout. O que acham? @wiliamsouza alguma sugestão?

**Comment by ramiroluz** [comment]
Beleza, mas eu provavelmente só poderei na sexta.

2015-09-16 16:52 GMT-03:00 Leonardo Rocha notifications@github.com:

> @ramiroluz https://github.com/ramiroluz peço desculpas pois ainda não
> consegui montar o vídeo pra mostrar como utilizar o Hangout. Penso que
> seria interessante ter as duas pontas, a pessoa que gera a transmissão e a
> pessoa que participa dela, pra mostrar da maneira mais real possível como
> funciona a ferramenta. Assim sendo, pensei em marcar com um de vocês para
> que façamos as gravações pra gerar o tutorial ensinando como utilizar o
> Hangout. O que acham? @wiliamsouza https://github.com/wiliamsouza
> alguma sugestão?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GruPyPR/encontros/issues/3#issuecomment-140868247.

## 

## 

-- Ramiro Batista da Luz
-- (41) 9173-2231
-- http://www.ramiroluz.eti.br
