### ISSUE TITLE
Documentar o uso do slack

### ISSUE THREAD

**Issue by wiliamsouza** [GruPyPR/grupypr.github.io#6]
Escrever sobre a integração com irc e app para telefone

**Comment by ellisonleao** [comment]
Android: https://play.google.com/store/apps/details?id=com.Slack&hl=pt_BR
iOS:  https://itunes.apple.com/br/app/slack-team-communication/id618783545?mt=8
MacOS: https://itunes.apple.com/br/app/slack/id803453959?mt=12
Windows: https://slack.com/ssb/download-win

**Comment by wiliamsouza** [comment]
# Slack

O que é?

O slack é uma aplicação de mensagens para times, tem integração com IRC, app para telefone, e uma interface web maneira e fácil de usar.

Como começar?

Abra o este [link](https://grupypr.herokuapp.com/) e digite no seu email, você deve receber uma email com as instruções, conclua seu cadastro seguindo link do email e escolha um usuário e digite uma senha. Pronto!

Se precisar de ajuda para configurar outros clientes só deixar um pergunta no canal [geral](https://grupypr.slack.com/messages/geral/).

**Comment by ellisonleao** [comment]
Adicionar a badge do slack no README #1 também. 

```
[![](http://grupypr.herokuapp.com/badge.svg)](https://grupypr.herokuapp.com/)
```

[![](http://grupypr.herokuapp.com/badge.svg)](https://grupypr.herokuapp.com/)

**Comment by wiliamsouza** [comment]
Feito! PR #1  commit 906e343
